# Generated by Django 4.1.3 on 2022-11-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myInventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_stock',
            field=models.IntegerField(default=0),
        ),
    ]
